"""Add ProjectSummary model

Revision ID: 5fd95388db30
Revises: b56a5cd016ee
Create Date: 2025-07-31 15:21:23.861679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd95388db30'
down_revision = 'b56a5cd016ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('module_answers', sa.JSON(), nullable=False),
    sa.Column('combined_summary', sa.Text(), nullable=False),
    sa.Column('modules_processed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_summary', 'project_summaries', ['project_id'], unique=False)
    op.create_index('idx_summary_type', 'project_summaries', ['project_id', 'summary_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_summary_type', table_name='project_summaries')
    op.drop_index('idx_project_summary', table_name='project_summaries')
    op.drop_table('project_summaries')
    # ### end Alembic commands ### 